### PR TITLE
Bm 78/rss

### PR DESCRIPTION
**Pull request by blnkt**
Implements Rss Feed Blog Posts as a content element where you specify the site url (http://blog.manifoldapp.org), the feed url (http://blog.manifoldapp.org/feed/), and how many posts you want (3 for the time being).  In the Content Element model we look to grab the posts from the Cache if present and if not we save to the Cache and store for an hour so they're available on the next page load.  Includes HTML comments in the markup to indicate whether the blog posts are coming from the cache or not.

### CODE REVIEW

**Comment by zdavis** [comment]
What happens if the RSS feed isn't available? Test it with an invalid URL (to simulate the blog being offline). Make sure that in that case the HP still works. Ideally the content element just wouldn't render—we definitely don't want to get a 500 error or an exception.

Please also increase the cache time to 6 hours.

Thanks!

**Comment by lthurston** [comment]
A thought: we could also fetch the actual feed in the background (using October’s task scheduling), so the frontend doesn’t have to wait on a secondary HTTP request. Likely a rare case, but if the blog is ever offline and the cache expires a user will be waiting for that secondary request timeout before the page loads. I could assist with this today.

**Comment by zdavis** [comment]
Agree that background is better. If it's easy, great — I went with the just in time + caching approach in order to get it done by Tuesday.

**Comment by lthurston** [comment]
Ok, if we can get in done quickly — and I think we can — we’ll implement it. If Blake has a ton left to do, I can just do it myself.

**Comment by lthurston** [comment]
I did some stuff. Fetching of the RSS feed now happens only in the background. You can run `php artisan rss:fetch` or set up the scheduled task to run it automatically every five minutes. I wrote the fetcher in such as way as it should start trying to get the feed again before the actual cached feed data expires, thus preventing any race conditions between cache and page requests.

I haven't totally figured out the task scheduling -- it's behaving a little odd for me locally, and I'm not sure if it's actually running the fetch command, but we can figure that out quickly on Tuesday I think.

The RSS feed output on the frontend contains an HTML comment that says how long in minutes until the cache clears, which might be useful for debugging / verifying that it's working.

One thing we might want to add is caching of fallback data -- posts data that doesn't expire in case the blog is down for a longer period of time. It's so easy, that why not?

**Pull request merged**
